"""Add fields to Bakery model

Revision ID: 8c70906ea2db
Revises: e8e8292e8bc6
Create Date: 2025-12-01 12:25:23.505340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c70906ea2db'
down_revision = 'e8e8292e8bc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakeries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('popularity_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hype_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('opening_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=255), nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('popularity')
        batch_op.drop_column('opened_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakeries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opened_at', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('popularity', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('website')
        batch_op.drop_column('description')
        batch_op.drop_column('opening_date')
        batch_op.drop_column('hype_score')
        batch_op.drop_column('popularity_score')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
