"""Add osm_id to Bakery

Revision ID: 9d50644a955f
Revises: 8c70906ea2db
Create Date: 2025-12-03 15:55:52.790824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d50644a955f'
down_revision = '8c70906ea2db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakeries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('osm_id', sa.String(), nullable=True))
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_bakeries_osm_id'), ['osm_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakeries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bakeries_osm_id'))
        batch_op.alter_column('address',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('osm_id')

    # ### end Alembic commands ###
